services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prosets
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - prosets-network

  api:
    build:
      context: ./apps/api
      target: dev
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/prosets
      NODE_ENV: development
    volumes:
      - ./apps/api/src:/app/src
      - ./apps/api/prisma:/app/prisma
      - ./apps/api/nest-cli.json:/app/nest-cli.json
      - ./apps/api/tsconfig.json:/app/tsconfig.json
      - ./apps/api/tsconfig.build.json:/app/tsconfig.build.json
      - api_node_modules:/app/node_modules
    depends_on:
      - postgres
    networks:
      - prosets-network

  web:
    build:
      context: ./apps/web
      target: dev
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    volumes:
      - ./apps/web/src:/app/src
      - ./apps/web/public:/app/public
      - ./apps/web/next.config.ts:/app/next.config.ts
      - ./apps/web/.env.local:/app/.env.local
      - web_node_modules:/app/node_modules
    depends_on:
      - api
    networks:
      - prosets-network

volumes:
  pgdata:
  api_node_modules:
  web_node_modules:


networks:
  prosets-network:
    driver: bridge
